### ISSUE TITLE
Multiple sliders on the same page

### ISSUE THREAD

**Issue by sergiofornet** [DZuz14/react-hooks-image-slider#14]
When trying to use two (or more) sliders at the same time, the last one works properly but any other one transitions back and forth to active slide when arrows are clicked. I don't know why but `smoothTransition` is called twice so it transitions, then the slides are updated and then it transitions again.

Any clue on why is this happening?

**Comment by sergiofornet** [comment]
It seems the `transitionend` event is triggered twice for every slider on a page but the last. Using a ref to the slider and adding the listener to it instead of `window` did the trick for me.

**Comment by AvinashKomaturi** [comment]
Hey @sergiofornet, I am also facing the same issue. can you please explain to which component should I create ref?

**Comment by DZuz14** [comment]
Fixed via https://github.com/DZuz14/react-hooks-image-slider/pull/15 thank you!
