### ISSUE TITLE
Responsive translate

### ISSUE THREAD

**Issue by RubensTen** [DZuz14/react-hooks-image-slider#2]
Hello, I found a issue when I resize the window or container of slide.

The scenarie is:
* Load slide in the screen
* After click in arrow right to traslate the current slide
* Then resize the window or dimensions of container
* Then you can see that the currrent value of translateX are not is valid, because the slide  are not visible correctly

![image](https://user-images.githubusercontent.com/13072050/42254664-65e92254-7f0d-11e8-9e91-ec54b355e5be.png)

**Comment by DZuz14** [comment]
Yup you are totally right! Let me take a look into this!

**Comment by DZuz14** [comment]
So I feel that on window resize, we have to dynamically set the width of a slide to the size of the viewport. I havent had too much time to look into this, but do you have any suggestions?

In the css the .slide class is set to width of 100%, thats thats probably not going to fly on resize. Not sure though

**Comment by adwin5** [comment]
@DZuz14 @RubensTen I sent a PR for this. #5
