### ISSUE TITLE
Images end up not appearing after one cycle on mobile (iOS and Chrome)

### ISSUE THREAD

**Issue by briang123** [DZuz14/react-hooks-image-slider#20]
Upon navigating slide show on iPhone using chrome I experienced that after clicking the right arrow to go through all images it goes back to the first image but no images would be displayed. 

![Image](https://i.imgur.com/bMOkl4z.jpg)

**Comment by briang123** [comment]
Looks like when clicking the arrow buttons, the translateX value is exceeding the position of where the image actually is, but then it's playing catch up and rendering; however, seems to be a problem on mobile for whatever reason.

**Comment by DZuz14** [comment]
hmmmmm. i will check into this. thank you!

**Comment by DZuz14** [comment]
This is fixed I believe. Closing for now.
