### ISSUE TITLE
Multiple images per slide

### ISSUE THREAD

**Issue by DZuz14** [DZuz14/react-hooks-image-slider#7]
I am thinking that we might want to use real `<img />` elements instead of a div that sets the images as a background. 

**For example**: 
Let's say you want 3 images per slide, you could then use the [srcset](https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Responsive_images) attribute to show different sized images dependent on the width of the browser. This would require the developer(s) to create multiple copies of their images at different sizes prior to utilizing the Slider properly.

I think at least at first glance this is a decent idea, as it accounts for performance and won't load large image files on smaller devices.

**Comment by DZuz14** [comment]
Just a few quick thoughts as a brain dump on what I think it might take to make this happen:

- Instead of passing just an array of image links down to the slider as props, we might want to actually create an array of objects instead. This way the developer could customize every single slide to suit there needs. 

Here is a very naive example of what I was thinking:

```
const slides = [
    {
        // Breakpoints at which to display a different sized image.
        sizes: [480, 768, 1000],

        // Images could be absolute, relative, or complete URLs.
        content: ['https://images.somecoolstartup.com/mountain-view.jpg', './public/static/images/summer.jpg'],

        // Allow some separation between the slides if displaying more than 1 per.
        spacing: { amount: 2, unit: 'em' }
    },
    {
        sizes: [768, 1024],
        content: ['/var/www/html/static/img/night-sky.jpg']
    }
]
```

**Comment by erichodges** [comment]
Another option would be to use Cloudinary or similar to automatically load the required image size. I'm working on a project doing this with gatsby. It's way better than having the dev make a ton of different image sizes.

**Comment by DZuz14** [comment]
I haven't used it before, but if you upload images, you can tell their app to generate them for you, or does it automatically re-create the images in a few default sizes?

Either way, all the developer would need to do in that case is just paste in the url to each image hosted on their cloudinary account.

**Comment by erichodges** [comment]
IIRC, you set up the sizes you want for the srcset in the gatsby config and then all those sizes are generated by Cloudinary automatically. Then the browser gets what it needs from the srcset which you get from the graphql query.

**Comment by DZuz14** [comment]
Okay cool. I'm thinking about refactoring the master branch of this to actually become a library that can be used on NPM. I'll check out your repo, and perhaps we could hack on this feature in branch I'll create called `dynamic-images`. 

We can use your cloudinary account to test things out if you want.

**Comment by DZuz14** [comment]
Actually, it should prob be called `multiple-slides` since that's what the initial problem was.

**Comment by erichodges** [comment]
Cool, yeah that sounds great. We will need a way to chat that is encrypted. Maybe on discord such as reactiflux etc.
